// This function generates a random word and returns it.
function wordSelector() {
  // Words are from "npm install an-array-of-english-words" (https://github.com/words/an-array-of-english-words)

  // Words are retrieved in this line.
  let wordsRetrieval = require("an-array-of-english-words");
  // Retrieved words are stored in an array.
  let wordArray = wordsRetrieval.filter((d) => /fun/.test(d));
  // Index is generated by a random number multiplied by the length of the array and converted into an integer.
  let word = wordArray[Math.floor(Math.random() * wordArray.length)];
  // Randomly generated word is returned.
  return word;
}
export { wordSelector };
